import numpy as np 
array1 = np.array([33,22,66,44,11]) 
print("\nMean of Array1:", np.mean(array1)) 
print("Standard Deviation of Array1:", np.std(array1)) 
print("Maximum value in Array1:", np.max(array1)) 
print("Minimum value in Array1:", np.min(array1)) 
print("Sum of Array1:", np.sum(array1)) 
array1[0] = 100 
print("\nModified Array1 (first element changed to 100):", array1) 
array1[1:3] = [200, 300] 
print("Modified Array1 (elements 1 and 2 updated):", array1) 
array1_appended = np.append(array1, [400, 500]) 
print("Array1 after appending elements:", array1_appended) 
array1_inserted = np.insert(array1, 2, 250) 
print("Array1 after inserting 250 at index 2:", array1_inserted) 
array1_deleted = np.delete(array1, [1, 2]) 
print("Array1 after deleting elements at indices 1 and 2:", array1_deleted) 
print("\nSorting the array",array1) 
sorted_array = np.sort(array1) 
print("Sorted Array:", sorted_array) 
array2 = np.array([[3, 2, 1], [6, 5, 4],[0, 2, 3]]) 
print("\nOriginal 2D Array:\n", array2) 
sorted_array2_row = np.sort(array2, axis=1) 
print("2D Array sorted row-wise:\n", sorted_array2_row) 
sorted_array2_col = np.sort(array2, axis=0) 
print("2D Array sorted column-wise:\n", sorted_array2_col)
